//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TarkovAssistantWPF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TarkovAssistantWPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear drawings.
        /// </summary>
        internal static string CLEAR {
            get {
                return ResourceManager.GetString("CLEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle between all maps.
        /// </summary>
        internal static string CYCLE_MAP {
            get {
                return ResourceManager.GetString("CYCLE_MAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle between sub maps.
        /// </summary>
        internal static string CYCLE_SUB_MAP {
            get {
                return ResourceManager.GetString("CYCLE_SUB_MAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next map.
        /// </summary>
        internal static string NEXT_MAP {
            get {
                return ResourceManager.GetString("NEXT_MAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pan down.
        /// </summary>
        internal static string PAN_DOWN {
            get {
                return ResourceManager.GetString("PAN_DOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pan map left.
        /// </summary>
        internal static string PAN_LEFT {
            get {
                return ResourceManager.GetString("PAN_LEFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pan map right.
        /// </summary>
        internal static string PAN_RIGHT {
            get {
                return ResourceManager.GetString("PAN_RIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pan map up.
        /// </summary>
        internal static string PAN_UP {
            get {
                return ResourceManager.GetString("PAN_UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous map.
        /// </summary>
        internal static string PREV_MAP {
            get {
                return ResourceManager.GetString("PREV_MAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset map.
        /// </summary>
        internal static string RESET {
            get {
                return ResourceManager.GetString("RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to Customs.
        /// </summary>
        internal static string SETMAP_CUSTOMS {
            get {
                return ResourceManager.GetString("SETMAP_CUSTOMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to Factory.
        /// </summary>
        internal static string SETMAP_FACTORY {
            get {
                return ResourceManager.GetString("SETMAP_FACTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to Interchange.
        /// </summary>
        internal static string SETMAP_INTERCHANGE {
            get {
                return ResourceManager.GetString("SETMAP_INTERCHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to Reserve (Overview).
        /// </summary>
        internal static string SETMAP_RESERVE {
            get {
                return ResourceManager.GetString("SETMAP_RESERVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to Reserve (Bunker).
        /// </summary>
        internal static string SETMAP_RESERVE_TUNNELS {
            get {
                return ResourceManager.GetString("SETMAP_RESERVE_TUNNELS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to Shoreline.
        /// </summary>
        internal static string SETMAP_SHORELINE {
            get {
                return ResourceManager.GetString("SETMAP_SHORELINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to Woods.
        /// </summary>
        internal static string SETMAP_WOODS {
            get {
                return ResourceManager.GetString("SETMAP_WOODS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for an item....
        /// </summary>
        internal static string str_searchhint {
            get {
                return ResourceManager.GetString("str_searchhint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://s3.eu-west-2.amazonaws.com/jwscully.uk/tarkov-assistant/update.zip.
        /// </summary>
        internal static string update_data_url {
            get {
                return ResourceManager.GetString("update_data_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://s3.eu-west-2.amazonaws.com/jwscully.uk/tarkov-assistant/update_info.xml.
        /// </summary>
        internal static string update_xml_url {
            get {
                return ResourceManager.GetString("update_xml_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom in.
        /// </summary>
        internal static string ZOOM_IN {
            get {
                return ResourceManager.GetString("ZOOM_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom out.
        /// </summary>
        internal static string ZOOM_OUT {
            get {
                return ResourceManager.GetString("ZOOM_OUT", resourceCulture);
            }
        }
    }
}
