//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TarkovAssistantWPF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TarkovAssistantWPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear drawings.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle between all maps.
        /// </summary>
        internal static string CycleMap {
            get {
                return ResourceManager.GetString("CycleMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle between sub maps.
        /// </summary>
        internal static string CycleSubMap {
            get {
                return ResourceManager.GetString("CycleSubMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next map.
        /// </summary>
        internal static string NextMap {
            get {
                return ResourceManager.GetString("NextMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pan down.
        /// </summary>
        internal static string PanDown {
            get {
                return ResourceManager.GetString("PanDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pan map left.
        /// </summary>
        internal static string PanLeft {
            get {
                return ResourceManager.GetString("PanLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pan map right.
        /// </summary>
        internal static string PanRight {
            get {
                return ResourceManager.GetString("PanRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pan map up.
        /// </summary>
        internal static string PanUp {
            get {
                return ResourceManager.GetString("PanUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous map.
        /// </summary>
        internal static string PrevMap {
            get {
                return ResourceManager.GetString("PrevMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset map.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to Customs.
        /// </summary>
        internal static string SetMapCustoms {
            get {
                return ResourceManager.GetString("SetMapCustoms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to Factory.
        /// </summary>
        internal static string SetMapFactory {
            get {
                return ResourceManager.GetString("SetMapFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to Interchange.
        /// </summary>
        internal static string SetMapInterchange {
            get {
                return ResourceManager.GetString("SetMapInterchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to Reserve (Overview).
        /// </summary>
        internal static string SetMapReserve {
            get {
                return ResourceManager.GetString("SetMapReserve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to Reserve (Bunker).
        /// </summary>
        internal static string SetMapReserveTunnels {
            get {
                return ResourceManager.GetString("SetMapReserveTunnels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to Shoreline.
        /// </summary>
        internal static string SetMapShoreline {
            get {
                return ResourceManager.GetString("SetMapShoreline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to Woods.
        /// </summary>
        internal static string SetMapWoods {
            get {
                return ResourceManager.GetString("SetMapWoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for an item....
        /// </summary>
        internal static string str_searchhint {
            get {
                return ResourceManager.GetString("str_searchhint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://tarkov-assistant-publish.s3.eu-west-2.amazonaws.com/update.zip.
        /// </summary>
        internal static string update_data_url {
            get {
                return ResourceManager.GetString("update_data_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://tarkov-assistant-publish.s3.eu-west-2.amazonaws.com/update_info.xml.
        /// </summary>
        internal static string update_xml_url {
            get {
                return ResourceManager.GetString("update_xml_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom in.
        /// </summary>
        internal static string ZoomIn {
            get {
                return ResourceManager.GetString("ZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom out.
        /// </summary>
        internal static string ZoomOut {
            get {
                return ResourceManager.GetString("ZoomOut", resourceCulture);
            }
        }
    }
}
