name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: windows-latest

    env:
          Solution_Name: 'TarkovAssistantWPF.sln'
          Project_Application: 'TarkovAssistantWPF'
          Project_Installer: 'TarkovAssistantSetup'

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore dependencies for Application
      run: msbuild -t:restore .\TarkovAssistantWPF.csproj

        # Build actual application
    - name: Build Application
      run: msbuild $env:Solution_Name /t:$env:Project_Application /p:Configuration=Release

    - name: Build Installer
      run: |
        $devenv = & vswhere.exe '-property' productPath
        Start-Process -FilePath $devenv -ArgumentList '$env:Solution_Name /build Release /project $env:Project_Installer'
      
      
# run: devenv $env:Solution_Name /build Release /project $env:Project_Installer
