name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: windows-latest

    env:
          Solution_Name: 'TarkovAssistantWPF.sln'

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore dependencies
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=Release
    - name: Build
      run: msbuild /p:Configuration=Release
